openai_api_key: ${openai-api-key}
connections:
  - name: jaffle_shop_duckdb
    databaseName: university_sample
    schemaName: ${db-schema-DBT Connection}
    dbType: duckdb
    url: >-
      jdbc:duckdb:C:\Users\Edon\rosetta-dbt-studio-projects\dbtstudio_getting_started\rosetta\university_sample.duckdb
