name: CI
jobs:
  - name: build
    steps:
      - name: Build warehouse
        plugin: dbt@v1
        command: dbt build
      - name: Run data tests
        plugin: dbt@v1
        command: dbt test
  - name: teardown
    steps:
      - name: Clean up
        plugin: command@v1
        command: echo "TEARDOWN"
    type: cleanup