name: CI
jobs:
  - name: build
    steps:
      - name: Complie and build models
        plugin: dbt@v1
        command: dbt build
      - name: Generate docs
        plugin: dbt@v1
        command: dbt docs generate 
      - name: Test staging models
        plugin: dbt@v1
        command: dbt test --select staging
  - name: teardown
    steps:
      - name: Tear down environemnt
        plugin: command@v1
        command: echo "TEARDOWN"
    type: cleanup
